package com.redhat.bpm.process.languageproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Number")
   private java.lang.String number;
   @org.kie.api.definition.type.Label(value = "StreetName")
   private java.lang.String streetName;
   @org.kie.api.definition.type.Label(value = "City")
   private java.lang.String city;
   @org.kie.api.definition.type.Label(value = "Zip")
   private java.lang.String zip;
   @org.kie.api.definition.type.Label(value = "Country")
   private com.redhat.bpm.process.languageproject.Country country;

   public Address()
   {
   }

   public java.lang.String getNumber()
   {
      return this.number;
   }

   public void setNumber(java.lang.String number)
   {
      this.number = number;
   }

   public java.lang.String getStreetName()
   {
      return this.streetName;
   }

   public void setStreetName(java.lang.String streetName)
   {
      this.streetName = streetName;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getZip()
   {
      return this.zip;
   }

   public void setZip(java.lang.String zip)
   {
      this.zip = zip;
   }

   public com.redhat.bpm.process.languageproject.Country getCountry()
   {
      return this.country;
   }

   public void setCountry(
         com.redhat.bpm.process.languageproject.Country country)
   {
      this.country = country;
   }

   public Address(java.lang.String number, java.lang.String streetName,
         java.lang.String city, java.lang.String zip,
         com.redhat.bpm.process.languageproject.Country country)
   {
      this.number = number;
      this.streetName = streetName;
      this.city = city;
      this.zip = zip;
      this.country = country;
   }

@Override
public String toString() {
	return "Address [number=" + number + ", streetName=" + streetName
			+ ", city=" + city + ", zip=" + zip + ", country=" + country + "]";
}
   

}