package com.redhat.bpm.process.languageproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Country implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Country")
   private java.lang.String country;

   public Country()
   {
   }

   public java.lang.String getCountry()
   {
      return this.country;
   }

   public void setCountry(java.lang.String country)
   {
      this.country = country;
   }

   public Country(java.lang.String country)
   {
      this.country = country;
   }

}