package com.redhat.bpm.process.languageproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Country implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Country() {
    }

}