package com.redhat.bpm.process.languageproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "FirstName")
   private java.lang.String firstName;
   @org.kie.api.definition.type.Label(value = "LastName")
   private java.lang.String lastName;
   @org.kie.api.definition.type.Label(value = "Address")
   private com.redhat.bpm.process.languageproject.Address address;

   public Customer()
   {
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public com.redhat.bpm.process.languageproject.Address getAddress()
   {
      return this.address;
   }

   public void setAddress(
         com.redhat.bpm.process.languageproject.Address address)
   {
      this.address = address;
   }

   public Customer(java.lang.String firstName, java.lang.String lastName,
         com.redhat.bpm.process.languageproject.Address address)
   {
      this.firstName = firstName;
      this.lastName = lastName;
      this.address = address;
   }

}